################################################################################
# SPDX-License-Identifier: LGPL-3.0-only
#
# This file is part of sysrepo-mcp-server.
# Copyright (C) 2026 Loic JOURDHEUIL SELLIN <46419549+Geneo-5@users.noreply.github.com>
################################################################################
# -*- coding: utf-8 -*-
#
# sysrepo-mcp-server documentation build configuration file.
#
# This file is execfile()d with the current directory set to its
# containing dir.

import os

# -- General configuration ------------------------------------------------

extensions = [
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx_rtd_theme',
]

templates_path = ['_templates']

source_suffix = '.rst'

# The master toctree document.
root_doc = 'index'

# General information about the project.
project = u'sysrepo-mcp-server'
copyright = u'2026 Loic JOURDHEUIL SELLIN'
author = u'Loic JOURDHEUIL SELLIN'

# The version is injected by the build system (see the top-level Makefile).
version = os.getenv('VERSION', u'??')
release = version

# The language for content autogenerated by Sphinx.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore.
# `genindex.rst' is deliberately excluded: a source document named `genindex'
# shadows the general index page Sphinx generates itself. The index is linked
# from index.rst through :ref:`genindex` instead. The file can be removed.
exclude_patterns = ['_build', '_templates', '_doxygen', 'genindex.rst']

# The name of the Pygments (syntax highlighting) style.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- Options for HTML output ----------------------------------------------

html_theme = 'sphinx_rtd_theme'

html_theme_options = {
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    'style_nav_header_background': '#333333',
    # Toc options
    'collapse_navigation': True,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False,
}

# `_static' is only declared when it actually exists: Sphinx warns about
# missing static paths and the documentation is built with -W in CI.
if os.path.isdir(os.path.join(os.path.dirname(__file__), '_static')):
    html_static_path = ['_static']
else:
    html_static_path = []

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    'papersize': 'a4paper',
    # The font size ('10pt', '11pt' or '12pt').
    'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    'preamble': '',
}

# Note: `latex_appendices' is deliberately NOT set. The appendix documents
# (license, todo) are already reachable through the appendix toctree of
# index.rst; declaring them here as well would emit them twice in the PDF.

# Grouping the document tree into LaTeX files.
latex_documents = [
    (root_doc, 'sysrepo-mcp-server.tex',
     u'sysrepo-mcp-server Documentation',
     author, 'manual'),
]

# -- Options for manual page output ---------------------------------------

man_pages = [
    (root_doc, 'sysrepo-mcp-server',
     u'MCP server bridging AI agents and the sysrepo datastore',
     [author], 1)
]

# -- Options for Texinfo output -------------------------------------------

texinfo_documents = [
    (root_doc, 'sysrepo-mcp-server',
     u'sysrepo-mcp-server Documentation',
     author, 'sysrepo-mcp-server',
     u'MCP server bridging AI agents and the sysrepo datastore.',
     'Miscellaneous'),
]

# -- Options for intersphinx ----------------------------------------------

intersphinx_mapping = {}

# -- Options for Breathe (Doxygen integration) ----------------------------

# The Doxygen XML output is generated by the Makefile `doc' target into
# sphinx/_doxygen/xml (git-ignored). Breathe is only enabled when that
# directory exists, so `sphinx-build' also works without running Doxygen.

_doxygen_xml = os.path.join(os.path.dirname(__file__), '_doxygen', 'xml')

if os.path.exists(_doxygen_xml):
    extensions += ['breathe']
    breathe_projects = {'sysrepo-mcp-server': _doxygen_xml}
    breathe_default_project = 'sysrepo-mcp-server'
