################################################################################
# SPDX-License-Identifier: GPL-3.0-only
#
# This file is part of sysrepo-mcp-server.
# Copyright (C) 2026 Loic JOURDHEUIL SELLIN <46419549+Geneo-5@users.noreply.github.com>
################################################################################
# -*- coding: utf-8 -*-
#
# sysrepo-mcp-server documentation build configuration file, created by
# sphinx-quickstart.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming from Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.intersphinx',
              'sphinx.ext.todo',
              'sphinx.ext.mathjax',
              'sphinx.ext.ifconfig',
              'sphinx_rtd_theme',
              ]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The master toctree document.
root_doc = 'index'
master_title = u'sysrepo-mcp-server Documentation'

# General information about the project.
project = u'sysrepo-mcp-server'
copyright = u'2026 Loic JOURDHEUIL SELLIN'
author = u'Loic JOURDHEUIL SELLIN'

# The version info for the project you\'re documenting, acts as a replacement for
# |version| and |release|, also used in various other places throughout
# the built documents.
#
# The short X.Y version.
#version = u'0.1'
version = os.getenv('VERSION', u'??')

# The full version, including alpha/beta/rc tags.
#release = u'0.1'
release = version

# The language for content autogenerated by Sphinx.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories. Ignored patterns are always ignored.
exclude_patterns = ['_build', '_templates']

# The name of the Pygments (syntax highlighting) style.
pygments_style = 'sphinx'

# If true, `todo` and `TodoList` produce output, else they produce nothing.
todo_include_todos = True

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'sphinx_rtd_theme'

# Theme options
html_theme_options = {
        'canonical_url': '',
        'logo_only': False,
        'display_version': True,
        'prev_next_buttons_location': 'bottom',
        'style_external_links': False,
        'style_nav_header_background': '#333333',
        # Toc options
        'collapse_navigation': True,
        'sticky_navigation': True,
        'navigation_depth': 4,
        'includehidden': True,
        'titles_only': False,
}

# Per-page logo
# html_logo = None

# Add any paths that contain custom static files (such as style sheets)
html_static_path = ['_static']

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
# The paper size ('letterpaper' or 'a4paper').
'papersize': 'a4paper',

# The font size ('10pt', '11pt' or '12pt').
'pointsize': '10pt',

# Additional stuff for the LaTeX preamble.
'preamble': '',

# Latex style (set to "manual" for a man page style document)
'latex_style': 'manual',

# Reduce appendix space (set to True to use native latex_appendices
# scheme for appendix numbering)
'latex_appendices': True,
}

# Grouping the document tree into LaTeX files.
latex_documents = [
    (root_doc, 'sysrepo-mcp-server.tex',
     'sysrepo-mcp-server Documentation',
     'Loic JOURDHEUIL SELLIN', 'manual'),
]

# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (root_doc, 'sysrepo-mcp-server',
     'sysrepo-mcp-server Documentation', [author], 1)
]

# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files.
texinfo_documents = [
    (root_doc, 'sysrepo-mcp-server',
     'sysrepo-mcp-server Documentation',
     author, 'sysrepo-mcp-server',
     'One line description of project.',
     'Miscellaneous'),
]

# -- Options for Breathe (Doxygen integration) ----------------------------

# The Doxygen XML output is generated by the Makefile `doc` target into
# sphinx/_doxygen/xml (git-ignored). Breathe is only enabled when that
# directory exists, so `sphinx-build` also works without running Doxygen.
import os

if os.path.exists(os.path.join(os.path.dirname(__file__), '_doxygen', 'xml')):
    extensions += ['breathe']
    breathe_projects = {
        'sysrepo-mcp-server': os.path.join(os.path.dirname(__file__), '_doxygen', 'xml'),
    }
    breathe_default_project = 'sysrepo-mcp-server'
